clc;
numfiles=150;
pts=0:16;
pts=pts*(pi/8);
shapes=zeros(2,16,150);

for alpha=1:numfiles
    s='../../data/ellipse/data/';
    s=strcat(s,num2str(alpha));
    s=strcat(s,'.jpg');
    mat_im=imread(s);
    shapee=size(mat_im);
    bw=rgb2gray(mat_im);
    x=bw>100;
    %imshow(bw);
    
    %pause;
    %reference- https://blogs.mathworks.com/steve/2015/08/17/ellipse-visualization-and-regionprops/
    %%on manual checking the points checking the points generated by this
    %%method were correct. Therefore we used it.
    
    ellipse=regionprops('table',x,'Centroid','MajorAxisLength','MinorAxisLength','Orientation');
    center=ellipse.Centroid;
    a=ellipse.MajorAxisLength/2;
    b=ellipse.MinorAxisLength/2;
    x=center(1);
    y=center(2);
    thet=ellipse.Orientation;
    theta=deg2rad(thet);
    
    X=x+a*cos(pts)*cos(theta) - b*sin(pts)*sin(theta);
    Y=y+a*cos(pts)*sin(theta) + b*sin(pts)*cos(theta);
    %plot(X,Y,'r');
    
    X=X(:,1:16);
    Y=Y(:,1:16);
    shapes(1,:,alpha)=X;
    shapes(2,:,alpha)=Y;
    %pause;
    
end
% pause;

save('points.mat', 'shapes');